language: java

jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - SQ_SCANNER_DL=https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.1.zip
    - PATH=$PATH:/tmp/sonar-scanner-2.6.1/bin

  matrix:
    - SQ_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.6.zip SONAR_HOME=/tmp/sonarqube-5.6
    - SQ_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.0-RC1.zip SONAR_HOME=/tmp/sonarqube-6.0-RC1

install:
  - cd /tmp
  - wget -O sonarqube.zip $SQ_DL
  - unzip sonarqube.zip
  - wget -O sonarqube-scanner.zip $SQ_SCANNER_DL
  - unzip sonarqube-scanner.zip
  - cd -

script:
  - mvn clean install
  - cp sonar-jproperties-plugin/target/sonar-jproperties-plugin-*-SNAPSHOT.jar $SONAR_HOME/extensions/plugins
  - cd $SONAR_HOME/bin/linux-x86-64
  - ./sonar.sh start
  - cd ../../logs
  - tail -f sonar.log
  - cd
  - cd jproperties-checks/src/test/resources
  - sonar-scanner -Dsonar.projectKey=jproperties -Dsonar.projectName=jproperties -Dsonar.projectVersion=1 -Dsonar.sources=checks
